Development
Ispirett/apple_website_replica pull request #1
Opened 2019-04-01 21:17 UTC by Ispirett

Thanks for your time.  Also, search bar is animated :)

2019-04-01 23:09 UTC, zlayabekrija requested changes
Wonderful first attempt, but there are some things that need improvement. Please follow the comments I have left in the code.
If you have any questions, please contact me on slack.
When ready please resubmit the review request.
Happy coding 😄 .

2019-04-01 23:09 UTC, zlayabekrija commented on css/main.css
> +  background-size: 1440px 1315px;
Please let background image follow your header width, you can use any units of measurement for background size.

2019-04-01 23:09 UTC, zlayabekrija commented on css/main.css
> +  height: 1.2em;
breaking the order, it's unnecessary please remove it.

2019-04-01 23:09 UTC, zlayabekrija commented on index.html
> +            src="https://web.archive.org/web/20140301004610im_/http://images.apple.com/home/images/your_verse_title_small.png"
Image should be properly displayed, please adjust it, there are some parts on the bottom that shouldn't be seen.

2019-04-01 23:09 UTC, zlayabekrija commented on index.html
> +    <aside class="ad-area">
This area should follow the width of the screen, please adjust the width, and since this isn't aside, use maybe div or footer.

2019-04-01 23:09 UTC, zlayabekrija commented on index.html
> +
Please close the header here, and keep this content in main tag or div tag.

2019-04-02 21:19 UTC, zlayabekrija approved these changes
Great job. Thumbs up 👍 .
Good luck with future projects and happy coding.

2019-04-02 21:23 UTC, Ispirett commented
Thanks!!! and I will :) have a great day.

On Tue, Apr 2, 2019, 5:19 PM Zlatan <notifications@github.com> wrote:

> *@zlayabekrija* approved this pull request.
>
> Great job. Thumbs up 👍 .
> Good luck with future projects and happy coding.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Ispirett/apple_website_replica/pull/1#pullrequestreview-221908274>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AlAQD0b2Ori639y8IfefZy4VDLy76GIzks5vc8ltgaJpZM4cWqRA>
> .
>

2019-04-02 21:39 UTC, merged